language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

services:
  - xvfb

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

install:
  - npm install

script:
  - ng test ngx-library